package com.example.android.sunshine.app.model;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by coolm on 10/17/2016.
 */
public class Weather extends RealmObject {





    @PrimaryKey
    private String day;

    private String city;

    private double cityLatitude;

    private double cityLongitude;

    private String description;

    private long cityHighTemp;

    private long cityLowTemp;

    private int humidity;

    private double pressure;

    private double windSpeed;

    private  double windDirection;

    private String country;



    // Standard getters & setters generated by your IDE…




    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getDay() {
        return day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getCityHighTemp() {
        return cityHighTemp;
    }

    public void setCityHighTemp(long cityHighTemp) {
        this.cityHighTemp = cityHighTemp;
    }

    public long getCityLowTemp() {
        return cityLowTemp;
    }

    public void setCityLowTemp(long cityLowTemp) {
        this.cityLowTemp = cityLowTemp;
    }

    public double getCityLatitude() {
        return cityLatitude;
    }

    public void setCityLatitude(double cityLatitude) {
        this.cityLatitude = cityLatitude;
    }

    public double getCityLongitude() {
        return cityLongitude;
    }

    public void setCityLongitude(double cityLongitude) {
        this.cityLongitude = cityLongitude;
    }

    public String getCity(){

        return city;

    }

    public void setCity(String city){

        this.city = city;

    }

    public double getPressure(){

        return pressure;

    }

    public void setPressure(double pressure) {
        this.pressure = pressure;
    }

    public void setHumidity(int humidity) {
        this.humidity = humidity;
    }

    public int getHumidity() {
        return humidity;
    }

    public double getWindDirection() {
        return windDirection;
    }

    public void setWindDirection(double windDirection) {
        this.windDirection = windDirection;
    }

    public void setWindSpeed(double windSpeed) {
        this.windSpeed = windSpeed;
    }

    public double getWindSpeed() {
        return windSpeed;
    }
}